name: Deploy Story Book
on: "push"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codeÔ∏è
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and Build
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build-storybook
        working-directory: week4/solent-room-finder-week-4
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        working-directory: week4/solent-room-finder-week-4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: week-4-solutions # <---- you may need to update this. The branch the action should deploy to.
          FOLDER: docs-build # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
